apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    app.kubernetes.io/name: webserver
    app.kubernetes.io/component: frontend
spec:
 containers:
 - name: webserver
   image: 380544824653.dkr.ecr.us-east-1.amazonaws.com/mkhan348-docker-assignment:appv1.0
 
