apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    app: employees
    component: frontend
spec:
 containers:
 - name: webserver
   image: 380544824653.dkr.ecr.us-east-1.amazonaws.com/mkhan348-docker-assignment:appv1.0
   env:
   - name: DBHOST
     value: 10.96.179.176  # Replace with the hostname of your MySQL service
   - name: DBUSER
     value: root
   - name: DBPWD
     value: password  # Replace with your MySQL password
