---
apiVersion: apps/v1
kind: pod
metadata:
  name: mysql-pod
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: backend

spec:
  containers:
  - name: mysql-db
    image: 139675527364.dkr.ecr.us-east-1.amazonaws.com/k8s-assignment:mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: pass123  # Replace with your desired MySQL root password
    - name: MYSQL_DATABASE
      value: employees
    ports:
    - containerPort: 3306
      protocol: TCP
